<template>
  <AttractionsList :attractions="sortedAttractions" />
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import AttractionsList from './AttractionsList.vue';
import type { Attraction } from '@/types/activitie';

// Przykładowe dane atrakcji
const attractions = ref<Attraction[]>([
  {
    id: 1,
    photo: '',
    name: 'Wieża Eiffla',
    rating: 4.6,
    reviews: 125000,
    category: 'Zabytek',
    type: 'Zabytek',
    price: '€€',
    priceRange: '€€',
    distance: '5 min spacerem',
    duration: '2-3 godziny',
    wheelchairAccessible: true,
    openingHours: 'Czynne do 23:45',
    status: 'Otwarte',
    buttonText: 'Kup bilet',
  },
  {
    id: 2,
    photo: '',
    name: 'Luwr',
    rating: 4.8,
    reviews: 98000,
    category: 'Muzeum',
    type: 'Muzeum',
    price: '€€',
    priceRange: '€€',
    distance: '15 min spacerem',
    duration: '3-4 godziny',
    wheelchairAccessible: true,
    openingHours: 'Czynne do 18:00',
    status: 'Otwarte',
    buttonText: 'Kup bilet',
  },
  {
    id: 3,
    photo: '',
    name: 'Katedra Notre-Dame',
    rating: 4.7,
    reviews: 87000,
    category: 'Zabytek',
    type: 'Zabytek',
    price: 'Darmowe',
    priceRange: 'Darmowe',
    distance: '10 min spacerem',
    duration: '1-2 godziny',
    wheelchairAccessible: false,
    openingHours: 'W trakcie renowacji',
    status: 'Zamknięte',
    buttonText: 'Niedostępne',
  },
  {
    id: 4,
    photo: '',
    name: 'Arc de Triomphe',
    rating: 4.5,
    reviews: 72000,
    category: 'Zabytek',
    type: 'Zabytek',
    price: '€',
    priceRange: '€',
    distance: '8 min spacerem',
    duration: '1 godzina',
    wheelchairAccessible: true,
    openingHours: 'Czynne do 22:30',
    status: 'Otwarte',
    buttonText: 'Kup bilet',
  },
  {
    id: 5,
    photo: '',
    name: 'Sacré-Cœur',
    rating: 4.6,
    reviews: 95000,
    category: 'Zabytek',
    type: 'Zabytek',
    price: 'Darmowe',
    priceRange: 'Darmowe',
    distance: '20 min taksówką',
    duration: '1-2 godziny',
    wheelchairAccessible: false,
    openingHours: 'Czynne do 22:15',
    status: 'Otwarte',
    buttonText: 'Zwiedzaj',
  },
  {
    id: 6,
    photo: '',
    name: 'Muzeum Orsay',
    rating: 4.7,
    reviews: 76000,
    category: 'Muzeum',
    type: 'Muzeum',
    price: '€€',
    priceRange: '€€',
    distance: '12 min spacerem',
    duration: '2-3 godziny',
    wheelchairAccessible: true,
    openingHours: 'Czynne do 18:00',
    status: 'Otwarte',
    buttonText: 'Kup bilet',
  },
  {
    id: 7,
    photo: '',
    name: 'Pałac Wersalski',
    rating: 4.8,
    reviews: 112000,
    category: 'Zabytek',
    type: 'Zabytek',
    price: '€€€',
    priceRange: '€€€',
    distance: '45 min pociągiem',
    duration: '4-5 godzin',
    wheelchairAccessible: true,
    openingHours: 'Czynne do 18:30',
    status: 'Otwarte',
    buttonText: 'Kup bilet',
  },
  {
    id: 8,
    photo: '',
    name: 'Panteon',
    rating: 4.5,
    reviews: 45000,
    category: 'Zabytek',
    type: 'Zabytek',
    price: '€',
    priceRange: '€',
    distance: '18 min spacerem',
    duration: '1-2 godziny',
    wheelchairAccessible: true,
    openingHours: 'Czynne do 18:00',
    status: 'Otwarte',
    buttonText: 'Kup bilet',
  },
  {
    id: 9,
    photo: '',
    name: 'Centrum Pompidou',
    rating: 4.4,
    reviews: 68000,
    category: 'Muzeum',
    type: 'Muzeum',
    price: '€€',
    priceRange: '€€',
    distance: '16 min spacerem',
    duration: '2-3 godziny',
    wheelchairAccessible: true,
    openingHours: 'Czynne do 21:00',
    status: 'Otwarte',
    buttonText: 'Kup bilet',
  },
  {
    id: 10,
    photo: '',
    name: 'Ogrody Luksemburskie',
    rating: 4.7,
    reviews: 89000,
    category: 'Park',
    type: 'Park',
    price: 'Darmowe',
    priceRange: 'Darmowe',
    distance: '14 min spacerem',
    duration: '1-2 godziny',
    wheelchairAccessible: true,
    openingHours: 'Otwarte do zmroku',
    status: 'Otwarte',
    buttonText: 'Zwiedzaj',
  },
]);

const sortedAttractions = computed(() => attractions.value);
</script>
